language: android
dist: trusty

jdk:
  - oraclejdk8

sudo: false

android:
  components:
    - tools

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_cache:
  # Do not cache a few Gradle files/directories (see https://docs.travis-ci.com/user/languages/java/#Caching)
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    # Gradle dependencies
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

    # Android build cache (see http://tools.android.com/tech-docs/build-cache)
    - $HOME/.android/build-cache

env:
  global:
    - ADB_INSTALL_TIMEOUT=8
    - API=19 
    - EMU_FLAVOR=default
    - ABI=x86
    - ANDROID_HOME=/usr/local/android-sdk
    - ANDROID_SDK_ROOT=$ANDROID_HOME
    - TOOLS=${ANDROID_HOME}/tools
    - PATH=${ANDROID_HOME}:${ANDROID_HOME}/emulator:${TOOLS}:${TOOLS}/bin:${ANDROID_HOME}/platform-tools:${PATH}

install:
  - echo 'count=0' > /home/travis/.android/repositories.cfg
  - echo y | sdkmanager "platform-tools" >/dev/null
  - echo y | sdkmanager "tools" >/dev/null
  - echo y | sdkmanager "build-tools;28.0.3" >/dev/null
  - echo y | sdkmanager "platforms;android-$API" >/dev/null
  - echo y | sdkmanager "platforms;android-28" >/dev/null
  - echo y | sdkmanager --channel=4 "emulator" >/dev/null
  - echo y | sdkmanager "extras;android;m2repository" >/dev/null
  - echo y | sdkmanager "system-images;android-$API;$EMU_FLAVOR;$ABI" >/dev/null
  - echo no | avdmanager create avd --force -n test -k "system-images;android-$API;$EMU_FLAVOR;$ABI" -c 10M
  - emulator -verbose -avd test -no-accel -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048 &

before_script:
  - ./gradlew :app:assembleDebug :app:assembleAndroidTest
  - android-wait-for-emulator
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82

script:
  - ./gradlew fullCoverageReport

after_success:
- bash <(curl -s https://codecov.io/bash) -f ./app/build/reports/jacoco/fullCoverageReport/fullCoverageReport.xml

deploy:
  skip_cleanup: true
  provider: script
  script: 
    openssl aes-256-cbc -K $encrypted_9ceb0e392b9e_key -iv $encrypted_9ceb0e392b9e_iv -in gianpamx.tar.enc -out gianpamx.tar -d ;
    tar -xvf gianpamx.tar -C app/ ;
    ./gradlew :app:publish
  on:
    branch: master
